### ISSUE TITLE
hubiC support

### ISSUE THREAD

**Issue by szepeviktor** [Vlad1mir-D/cloudfuse#3]
Please consider hubiC support.
hubiC uses OAuth2 for authentication.
example: https://api.hubic.com/sandbox/

**Comment by Am1GO** [comment]
You could use either https://github.com/TurboGit/hubicfuse or https://github.com/oderwat/hubic2swiftgate

**Comment by szepeviktor** [comment]
Thank you!
I am waiting for the [s3ql hubiC support](https://bitbucket.org/nikratio/s3ql/issue/132/add-oauth2-authentication-for-swift).
